### ISSUE TITLE
Open source the repo

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/geoplumber#12]
- [x] README contains basic use case
- [x] Basic functions are ship shape
- [x] Clean git history.
- [x] package.json in README 
- Anything else?

**Comment by layik** [comment]
Travis build triggered.

**Comment by mpadge** [comment]
Nice! Did you just get rid of all the history, or did you BFG it?

**Comment by layik** [comment]
It was not actually big (2.2mb) but decided to just get rid of all my "pseudo" private commits.

**Comment by layik** [comment]
It is backed up :)

**Comment by layik** [comment]
Now trying to make Travis happy.
