### ISSUE TITLE
Installing create-react-app npm package

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#18]
We have created a helper function which now looks a little more harder than it looks.
[Apparently](https://stackoverflow.com/q/23186960), and understandably, it is not easy to ask current user to "sudo".

For geoplumber to function, we do need an npm package. We know npm packages can be installed anywhere and "globally". How should we deal with this?

1. Force user to "sudo npm i -g create-react-app". (Clean)
2. Allow user to install `create-react-app` somwhere and create the geoplumber app "within" it. (sloppy)
3. Allow both (current state, hard to implement and sloppy)

Any tips is great.

**Comment by layik** [comment]
will revisit this at some point.

**Comment by mpadge** [comment]
I don't think you need to. Especially from the CRAN view, the `sudo` operations won't ever pass, because they won't translate into windows. For that, you just have to pre-specify system requirements, so the current solution really is the only generally acceptable approach, I'd suggest.

**Comment by Robinlovelace** [comment]
Thanks for the input Mark, sounds good!

**Comment by layik** [comment]
Great.

**Comment by layik** [comment]
Just to prevent this issue popping up again. The reason was this: is there a way we could let the user setup their npm as outlined here? https://docs.npmjs.com/getting-started/fixing-npm-permissions

The answer is the same as this issue. There is some form npm setup by the user and it should not be the concern of this package.
