### ISSUE TITLE
Write vignette

### ISSUE THREAD

**Issue by mpadge** [ATFutures/geoplumber#24]
If it's okay, I'd like to self-nominate this one, because it seems the best way for me to get a sufficiently deep grasp of this amazing work. Plus, having an outsider write a vignette is very often the best way! :smile:

**Comment by layik** [comment]
> If you write a nice vignette, consider submitting it to the Journal of Statistical Software or The R Journal. Both journals are electronic only and peer-reviewed. Comments from reviewers can be very helpful for improving the quality of your vignette and the related software.

http://r-pkgs.had.co.nz/vignettes.html

**Comment by layik** [comment]
Should be next, now that we have few use cases to present. Also to get it ready for CRAN.

**Comment by mpadge** [comment]
And I'm still self-nominated in spite of my not having done anything yet. But with @silberzwiebel now cracking on this, our joint use case for moveability will be sufficient motivation for me to do this. If I don't find time tomorrow, I promise I'll be on to it by next week.

**Comment by Robinlovelace** [comment]
One option @layik is to move parts of the gisruk abstract (especially the schematic diagram) into a skeleton vignette.

**Comment by layik** [comment]
Thanks @mpadge. Agree @Robinlovelace, hopefully Mark/Thomas will kindly remove it from the README.

**Comment by layik** [comment]
Will be putting in the GISRUK paper into the vignette.

**Comment by layik** [comment]
Written.
