### ISSUE TITLE
Create max augement to set number of features to show on map with sensible default

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/geoplumber#25]

**Comment by Robinlovelace** [comment]
Here's the beginnings of making the max arg work:

```
# Below is part of stats19 endpoint:
library(stplanr)
ac <- read_stats19_ac() # 214 mb compressed data
names(ac)
ac = ac[!is.na(ac$Latitude), ]
ac_sf = sf::st_as_sf(ac, coords = c("Longitude", "Latitude"), crs = 4326)
b = spData::lnd

ac_lnd = ac_sf[b, ]
plot(sf::st_geometry(ac_lnd[sample(nrow(ac_lnd), 1000), ]))
ac_sf_mini = ac_sf[1:1000, ]
#' @get /api/uol
uol_geojson <- function(res){
  res$body <- ac_sf_mini
  res
}
```

**Comment by Robinlovelace** [comment]
Heads-up @symbolixAU - @layik the tag didn't work 1st time around. Maybe open-up an issue if one would be appreciated 😄

**Comment by layik** [comment]
Done https://github.com/SymbolixAU/geojsonsf/issues/29

**Comment by SymbolixAU** [comment]
closed in https://github.com/SymbolixAU/geojsonsf/issues/29#issuecomment-422572949

you need to use `sf_geojson()` to from `sf` to geojson

**Comment by layik** [comment]
Thanks @SymbolixAU 

```

**Comment by layik** [comment]
Other tickets just jump the priority queue over this one.

**Comment by layik** [comment]
title not clear so closing but happy to reopen again.
