### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/geoplumber#3]
To run tests on travis or another CI service. E.g. with:

```r
usethis::use_travis()
```

**Comment by Robinlovelace** [comment]
Looks like it's not auto restarting the build now. The link between travis and github seems to have stopped: no ticks or xs by the commit messages: https://github.com/ATFutures/geoplumber/commits/master Any ideas @layik ?

**Comment by layik** [comment]
Not happy with the list of apt dependencies added, but I like a build happening so trying again.

**Comment by layik** [comment]
https://travis-ci.org/ATFutures/geoplumber/builds/428931410

**Comment by layik** [comment]
Done!
