### ISSUE TITLE
GeoJSONComponent duplicated

### ISSUE THREAD

**Issue by mpadge** [ATFutures/geoplumber#32]
I see the following warning on `gp_build()`:
```
Creating an optimized production build... [0/250]
Failed to compile.

./src/Welcome.js
Module build failed: Duplicate declaration "GeoJSONComponent"

   9 | import './App.css';
  10 | 
> 11 | import GeoJSONComponent from './components/GeoJSONComponent.jsx';
     |        ^
  12 | export default class Welcome extends Component {
  13 |     constructor(props) {
  14 |         super(props);
```
In [`./inst/src/js/Welcome.js`](https://github.com/ATFutures/geoplumber/blob/master/inst/js/src/Welcome.js), you've got (current [Line#7](https://github.com/ATFutures/geoplumber/blob/master/inst/js/src/Welcome.js#L7)):
```
import GeoJSONComponent from './components/GeoJSONComponent.jsx';
```
and then in [`R/gp_add_geojson.R`](https://github.com/ATFutures/geoplumber/blob/master/R/add_geojson.R), you've also got two lines which construct an identical statement by default (current [Line#31](https://github.com/ATFutures/geoplumber/blob/master/R/add_geojson.R#L31) and [47](https://github.com/ATFutures/geoplumber/blob/master/R/add_geojson.R#L47)). The names of the imported objects for one of these statements should be changed to avoid this duplication.

**Comment by layik** [comment]
Thanks again Mark, will check test case and push.

**Comment by layik** [comment]
Clsoing this @mpadge. Reopen if not done properly.

**Comment by mpadge** [comment]
Great fix! Thanks
