### ISSUE TITLE
Points: use Circle/Marker,  setting to choose and cluster if possible!

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#35]
`add_geojson` could have a param to view as "cirlce" as default is marker. 1000 points looks like this.

Also, lets cluster them if they are markers. 
![screenshot from 2018-09-18 14-25-14](https://user-images.githubusercontent.com/408568/45690680-d75f7280-bb4e-11e8-96a1-e1ee9dca05df.png)

plot()
![rplot](https://user-images.githubusercontent.com/408568/45690742-f4944100-bb4e-11e8-89b7-ec90fc32dbfa.png)

**Comment by layik** [comment]
Working on this.

**Comment by layik** [comment]
So as starting point, we can now set front end to visualise points either as markers or circles, if we don't, it will decide based on a 10 point threshold to decide between marks and circles. 

Circle "styles", would be next (separate issue/card perhaps)

We will leave clustering markers for now. It raises other design issues at this stage and not necessary.

<img width="420" alt="screen shot 2018-09-21 at 14 43 37" src="https://user-images.githubusercontent.com/408568/45885123-89947580-bdad-11e8-940e-dc975f2a54eb.png">

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by Robinlovelace** [comment]
Next-up I guess: colour schemes and legends.

**Comment by layik** [comment]
Indeed @Robinlovelace. 
Thanks @mpadge I get to love React even more tbh.
What is next is actually a serious take on Shiny. Commit coming!
