### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by mpadge** [ATFutures/geoplumber#36]
Coz we're going to have to do it, and @layik I guess you're the only one in a position here to do this. How difficult will it be?

**Comment by layik** [comment]
Should really not be so hard. R has all the power needed.

**Comment by layik** [comment]
From @mpadge on Slack: https://github.com/r-hub/rhub

**Comment by layik** [comment]
There is reason to bring this forward.

**Comment by layik** [comment]
Here we are https://github.com/ATFutures/geoplumber/commit/b21120a26343225db8839c56847811f9d0a63ad4

**Comment by layik** [comment]
My tests all run fine, I will close this ticket and if there are any issues related to this we can reopen. Thanks @mpadge!
