### ISSUE TITLE
Write proper tests

### ISSUE THREAD

**Issue by mpadge** [ATFutures/geoplumber#37]
I suggest that we actually implement full tests and just switch them off with `testthat::skip_on_cran()` or [equivalent](https://github.com/ATFutures/dodgr/blob/master/tests/testthat/test-dodgr.R#L3-L4). When we do #36, we can also use appveyor, and then with travis we'll be able to test Windows, Linux, and Apple OSs.

**Comment by layik** [comment]
And I need more time with "testthat" :)

**Comment by layik** [comment]
Plenty [here and other test files](https://github.com/trestletech/plumber/blob/master/tests/testthat/test-plumber.R) to make sure:
1. Default (inst) plumber.R is tested.
2. Use it to assist users as they start adding endpoints into their own geoplumber apps
3. Also, I learn `testthat`

**Comment by mpadge** [comment]
@layik Initial full test added with [this commit](https://github.com/ATFutures/geoplumber/commit/ce86c033c3c385d81ebe54c893433745ae486a59). I'll wait and see what travis says ...

**Comment by mpadge** [comment]
Thanks to a great morning's teamwork, first full install and build test now passes. @layik Now that we've got coverage reports, we can see that the biggest missing (i.e., untested!) pieces are `endpoint_from_clip()` (57 lines) and `plumb()` (18 lines). I'll try to find a way to test the latter; do you want to write tests for the former? That'd be cool. If we had full coverage of those, we'd have 72%, which would be fine for our purposes, coz we'll obviously never be able to test everything here.

**Comment by layik** [comment]
I will @mpadge, thanks to the tempdir should be straightforward. Leave it with me.

**Comment by layik** [comment]
`plumb` has to wait until I work out how it is done in original `plumber` repo.

**Comment by layik** [comment]
I *hope* the mock test is done "properly" @mpadge.

**Comment by layik** [comment]
I cannot see how "run" is tested, but I can see that each endpoint can be "called" or "exec"ed?
https://github.com/trestletech/plumber/blob/master/tests/testthat/test-plumber.R#L115

**Comment by layik** [comment]
Sounds like "mock" is not taken into account here
https://codecov.io/gh/ATFutures/geoplumber/tree/master/R

**Comment by layik** [comment]
https://github.com/ATFutures/geoplumber/commit/99b4e636e27a31639cfa4466b21e6d65b2495cb7

**Comment by layik** [comment]
As it is not a "scoped" title @mpadge I think we can close this ticket. The fact that there is no React/frontend test code is clearly there. We can open new issue tickets to make the future "components" covered or indeed to further cover the R side.

**Comment by layik** [comment]
I am aware [this](url
https://github.com/ATFutures/geoplumber/commit/81c6bf007db421acd017cf8ac9704886990f2052) has brought the code coverage down considerably but we know why and I hope the package would grow to make the create, build and plumb functions the lesser part of the package.
