### ISSUE TITLE
Test case gcvt

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/geoplumber#39]
@cmcaine has developed a web app using npm package: https://github.com/IntegratedTransportPlanning/gcvt

We talked about the possibility of using geoplumber to set-up the JS side. A good use case I think. Possible topic for a minihack.

**Comment by layik** [comment]
Thanks Robi. 

I will have a look and happy to help with front end. I am getting into liking the freedom of plumber/httupv server side work. And for front end I can only focus on React for now @cmcaine. Sorry if can’t do more.

**Comment by Robinlovelace** [comment]
@cmcaine does Thursday morning next week work for you?

**Comment by layik** [comment]
So our meeting today clarified where the two projects stand and the amount of overlap in between. But will leave this to you @Robinlovelace to close/elaborate etc.
