### ISSUE TITLE
Add grow slider 

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/geoplumber#41]
To show an example of interactivity on the JS side.

**Comment by layik** [comment]
Few more tickets of prep and ship shaping other functions and will get on to this.

**Comment by layik** [comment]
Working on this.

**Comment by layik** [comment]
Not sure if a reprex would work but this should work on your machine
```
# git pull 
devtools::install()
gp_create()
# or just switch to a geoplumber app (should be backward compatible)
gp_sf(with_slider = TRUE)
```
That should give you
1. traffic locations data with cirlces
2. slider would grow the circles between 1 - 10

**Comment by layik** [comment]
<img width="1177" alt="screen shot 2018-10-06 at 11 36 02" src="https://user-images.githubusercontent.com/408568/46570441-25041980-c95c-11e8-8593-977ee3bbbf42.png">
<img width="1175" alt="screen shot 2018-10-06 at 11 36 19" src="https://user-images.githubusercontent.com/408568/46570442-259cb000-c95c-11e8-9e52-97f256f402c7.png">
<img width="1175" alt="screen shot 2018-10-06 at 11 36 37" src="https://user-images.githubusercontent.com/408568/46570443-259cb000-c95c-11e8-8ffe-64c8e33558c7.png">

more complicated examples on the way.

**Comment by layik** [comment]
working on adding "linewidth" to leaflet with slider component.

**Comment by layik** [comment]
linewidth added, one of the previous commits.

With last [push](https://github.com/ATFutures/geoplumber/commit/6e016669f73689c23d6c68c7c95adcccaf0bf42e), following should do a "server side" `sf` st_buffer of the `uni_poly` object. This is clearly easy on client side, using js packages like D3 or turf. What we are demonstrating here is React/R (geoplumber) can easily query the server for "R" power.

The reliance on JS/React knowledge in the snippet below will always be there until, someone, somewhere would write a package that would be able to "sythensize" React from R. I attribute this simplicity in the code to React's state/props paradigm.

```
gp_create(tolower(tempdir()))
cw <- setwd(tolower(tempdir()))
gp_is_wd_geoplumber()
gp_add_slider(
  min = 0.001,
  max = 0.01,
  step = 0.001
)
gp_change_file(
  path = "src/Welcome.js",
  what = '<GeoJSONComponent fetchURL={"http://localhost:8000/api/uol?grow=" + this.state.sliderInput} />
',
  pattern = '<GeoJSONComponent fetchURL="http://localhost:8000/api/uol" />',
  replace = TRUE,
  verbose = TRUE
)
gp_build()
gp_plumb()
```

<img width="1652" alt="screen shot 2018-10-09 at 21 46 51" src="https://user-images.githubusercontent.com/408568/46697721-2d36b000-cc0d-11e8-8f72-b0be967a42ce.png">

<img width="1667" alt="screen shot 2018-10-09 at 21 46 37" src="https://user-images.githubusercontent.com/408568/46697760-43447080-cc0d-11e8-9c35-631710c6d605.png">

We can close this and #43

**Comment by Robinlovelace** [comment]
This is awesome. Just playing with it now. Yes, I say, fantastic work.

**Comment by Robinlovelace** [comment]
Proof that the above code is reproducible: just reproduced it, as illustrated below, this project I think is close to take off :rocket: 

![peek 2018-10-09 22-19](https://user-images.githubusercontent.com/1825120/46699371-7f79d000-cc11-11e8-9716-e1223296c7d6.gif)

**Comment by Robinlovelace** [comment]
Quick question/idea @layik: I think it would be interesting and very educational to show similar functionality done on the client side, e.g. with https://github.com/Turfjs/turf/tree/master/packages/turf-buffer 

The benefit of the js solution is not just speed/resource use: it also has sensible units (I suggest km in this case)!

An example that would go really well in a vignette/paper on the subject (the vignette can become a paper). Heads-up @mpadge on that ; )

**Comment by layik** [comment]
ah, just see this. Thanks for checking on turf-buffer! Absolutely. Glad I was right in my assumption. Creating a new issue this one has dragged a little bit too far :)

**Comment by layik** [comment]
The GIF is going into the .Rmd. Thank you @Robinlovelace.
