### ISSUE TITLE
Add more example datasets

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/geoplumber#45]
- [x] Road crashes in Southwark
- [x] Road network in Southwark

Allow different layers to be shown.

**Comment by layik** [comment]
Will get to this at some point!

**Comment by layik** [comment]
Will be great Robin.

**Comment by layik** [comment]
Of course subset it with road names.
![screenshot from 2018-10-10 21-27-55](https://user-images.githubusercontent.com/408568/46764103-78b39180-ccd3-11e8-939b-9072a056de1f.png)

**Comment by Robinlovelace** [comment]
Looks quite disconnected. But yes, that will provide at least 3 layers. Only missing layer type is polygons when that goes in an there's open data on that.

**Comment by layik** [comment]
I think the disconnect is more to do with the roads where sample was taken, yes I can see potential within road disconnects, too.

**Comment by layik** [comment]
Just remembered, I have done this rather big (13mb only geometry) network using awesome osmdata @Robinlovelace, not sure if that is what you mean in the other thread with @mpadge.
![screenshot from 2018-10-12 11-17-43](https://user-images.githubusercontent.com/408568/46863882-8884c000-ce10-11e8-8141-8badcf76216b.png)

**Comment by Robinlovelace** [comment]
It's too big to fit on CRAN as an example dataset (5MB limit). Suggest creating a 'core network', e.g. only A and B roads and ones with traffic counts on and ones that connect between them. Creating a minimal (~100 kB) core network in a small area of London is not as simple as it first may seem!

**Comment by layik** [comment]
> Creating a minimal (~100 kB) core network in a small area of London is not as simple as it first may seem!
Correct.

**Comment by layik** [comment]
Primary roads only, 1,107,896 bytes
![screenshot from 2018-10-12 17-03-38](https://user-images.githubusercontent.com/408568/46880542-dca79880-ce40-11e8-9171-e8382300992f.png)

**Comment by layik** [comment]
I will leave it there, I have these saved in a separate project if we need them.

**Comment by Robinlovelace** [comment]
Looking good, suitable example dataset. Worth including with `usethis::use_data("traffic_network")` and documenting in `data.R`? I suspect so!

**Comment by layik** [comment]
Will do!

**Comment by layik** [comment]
If you are happy we can tick the second check box @Robinlovelace :)

Note: this type of data (one column geom sf objects) currently not "properly" rendered by geoplumber pending a slight change in #51 related to an underlying package.

**Comment by Robinlovelace** [comment]
Fantastic work, job done!

Related issue is that I cannot get it to show with `gp_sf()` even after coercing it to `sf` class. can you reproduce this? Job done in any case!

```r
devtools::install_github("ATFutures/geoplumber")
library(geoplumber)
sf:::plot.sfc_LINESTRING(traffic_network)
gp_create()
setwd("geoplumber/")
gp_sf(traffic_network) # error
tn = sf::st_sf(traffic_network)
gp_sf(tn) # not showing
```

**Comment by layik** [comment]
> Note: this type of data (one column geom sf objects) currently not "properly" rendered by geoplumber pending a slight change in #51 related to an underlying package.

**Comment by Robinlovelace** [comment]
Aha yes thanks for the clarification!
