### ISSUE TITLE
gp_sf renders geom only

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#51]

**Comment by layik** [comment]
Pending https://github.com/SymbolixAU/geojsonsf/issues/38

**Comment by layik** [comment]
`gp_sf(traffic_network, props_list = list())`
should give you this

<img width="645" alt="screen shot 2018-10-15 at 14 45 01" src="https://user-images.githubusercontent.com/408568/46954607-f0ddd680-d088-11e8-9c10-dc920bc4be24.png">

- [ ] hide if "dropdown" is empty (always good!)

**Comment by Robinlovelace** [comment]
Great work!

**Comment by layik** [comment]
https://github.com/ATFutures/geoplumber/commit/5b6446b1c42b29f313456fff7a722e2a71d9d3c7#diff-65b4dc2108ed3e8bdb33e6cd5f0b0d82L58
