### ISSUE TITLE
covr failing on Travis

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#54]
[Travis](https://travis-ci.org/ATFutures/geoplumber/jobs/447658102#L1900) log

**Comment by layik** [comment]
No passing!
https://travis-ci.org/ATFutures/geoplumber/builds/447708790

**Comment by Robinlovelace** [comment]
Yay! I had similar woes with stplanr as the build log here shows: https://github.com/ropensci/stplanr/pull/274

**Comment by layik** [comment]
not sure if this issue had anything to do with a PAT added to Travis, if it did, PAT has been added.
