### ISSUE TITLE
Feature request: for instance in `gp_sf`

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#60]
cc @silberzwiebel

**Comment by Robinlovelace** [comment]
I cannot think of any disadvantage of adding such a function, providing it doesn't lead to 'mission creep' (whereby more and more features and arguments are added to the function). A barebones thing will differentiate it from higher-level pkgs like `mapdeck`, `tmap` and `mapview`.

**Comment by layik** [comment]
Thanks @Robinlovelace. Agreed.

**Comment by layik** [comment]
we have a `gp_sf` which is not like the packages mentioned. It does talk to the backend. If there is an issue with `gp_sf` lets open new issues.
