### ISSUE TITLE
gp_unbuild, gp_clean, gp_rm_build or some function like that

### ISSUE THREAD

**Issue by mpadge** [ATFutures/geoplumber#65]
The `gp_erase()` function cleans everything, but it would also be useful to have a function that just cleans the build, not the whole project - meaning just removing the "build" and "node_modules" directories.

**Comment by layik** [comment]
Thanks @mpadge this is done now.

**Comment by mpadge** [comment]
That's great - this for me immediately enhances usability. Thanks!
