### ISSUE TITLE
Static geoplumber map

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#69]
At this point it should only export "geojson" or at least for this ticket. This was discussed in #44 briefly but worth its own ticket. Almost there with a ReactLeaflet template already committed into the templates, it would also mean being different to mapview, mapdeck and other awesome packages because it wold not be written in Shiny/vanillaJS.

**Comment by layik** [comment]
https://github.com/ATFutures/geoplumber/commit/4ee1aab3a082bd01785e21c9f2025f02591541c3

**Comment by layik** [comment]
Basics done. More would be reproducing leaflet or mapview. Will do a bit more to make it more useful but this can be closed.

**Comment by Robinlovelace** [comment]
`gp_map()` is an awesome function. Deserves to be on CRAN asap!

**Comment by layik** [comment]
We might as well upload it to user's GitHub "gist" or somewhere and `htmltools::includeHTML` for max reprex!
<img width="876" alt="Screenshot 2019-03-21 at 17 17 44" src="https://user-images.githubusercontent.com/408568/54771586-83b50b00-4bfd-11e9-94c1-0306a3b86b05.png">


I will get it to CRAN, promise :)
