### ISSUE TITLE
Stop swagger appearing

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#70]
Investigate this, does `gp_plumb` need to pass FALSE to `plumber`?

**Comment by layik** [comment]
@Robinlovelace I am struggling to reproduce this with current code. Could you please do from an R console outside Rstudio:

1. setwd() to a gp app
2. gp_plumb()

and see if it fires `localhost:8000/__swagger__`

it should not really

**Comment by layik** [comment]
Handled in plumber1.0? Reopen as needed.

**Comment by Robinlovelace** [comment]
Awesome, not tried it yet but great if that's now fixed. Look forward to taking geoplumber for another test drive!
