### ISSUE TITLE
Vignettes slow down build

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#75]
They are valuable resources, whether they need to be rebuilt every time the package is built, I am just not sure anymore.

**Comment by Robinlovelace** [comment]
If it's an issue with local build times, you could use the flag ` --no-vignettes` to not run R code in vignettes: https://support.rstudio.com/hc/en-us/articles/200486518-Customizing-Package-Build-Options

Another approach is to use `eval = FALSE`, something I do in this new stplanr vignette: https://ropensci.github.io/stplanr/articles/stplanr-od.html

It's annoying how long pkgs take to build and I've also wrestled with that question. Hope that helps...

**Comment by layik** [comment]
Maybe the same on Travis?

Thanks Robin. I think one of those would be good enough. I will see if I can push a commit. 

Thanks Robin!

**Comment by layik** [comment]
https://github.com/ATFutures/geoplumber/commit/24faf05d8a52c1ee895fddb50a900767d8b4dd8f has made the build pass but midnight Travis took 32 mins.

**Comment by layik** [comment]
Closing pending other opts.
