### ISSUE TITLE
Support for flowmap.gl

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/geoplumber#76]
Heads-up @layik, thanks to @symbolixau (let us know if you're thinking of doing anything with this and we can help) I just discovered this, which could solve sooo many problems in OD data mapping. https://github.com/teralytics/flowmap.gl

I notice it can be used with React already. Any chance of a wrapper so we can show OD data in R using this framework. That would be amazing.

**Comment by dcooley** [comment]
Yes I too have added a task to implement this - https://github.com/SymbolixAU/mapdeck/issues/223 - but mapdeck doesn't use react, so will need the .min.js version if it's made available. So I'm keen to see you get this working too.

**Comment by layik** [comment]
Thanks everyone, must fine time to get back on `geoplumber`.

**Comment by layik** [comment]
#79

**Comment by layik** [comment]
Right @Robinlovelace and @dcooley. Here is what I have been able to do in the eAtlas so far which is very basic uses of the layer (flowmap). The showcases on flowmap.blue is much better of course.

Dave, happy to contribute if I can, I should be able to get you a `.min.js` from the repo if not over confident here.

Data: 180k OD pair and twice so far crashed my 16gb MacBook Pro GPU.
<img width="1057" alt="Screenshot 2020-05-29 at 11 05 15" src="https://user-images.githubusercontent.com/408568/83249488-8e264980-a19e-11ea-985e-c0a11fa9a056.png">
<img width="1055" alt="Screenshot 2020-05-29 at 11 05 36" src="https://user-images.githubusercontent.com/408568/83249498-92eafd80-a19e-11ea-882e-cdfc86edad77.png">
![Uploading Screenshot 2020-05-29 at 11.21.02.png…]()

**Comment by layik** [comment]
the dots are not "points" they are "top flows" from the flowmap layer.

**Comment by Robinlovelace** [comment]
Nice!

**Comment by layik** [comment]
I think I see the best way to get this into `geoplumber` which has to be via `eAtlas` or another source. It is perfect for @dcooley to import into Mapdeck like other layers and maybe I should focus on helping (if needed) with the `min.js` needed for Dave to use.

The layer is similar to our own efforts of at least two new layers for DeckGL, namely the barvis and peak vis both from Washington Post work.

<img width="828" alt="Screenshot 2020-06-03 at 01 45 19" src="https://user-images.githubusercontent.com/408568/83942254-dde1c200-a7e9-11ea-8376-357932eb20e3.png">
Visualizing the swing to Conservatives.

<img width="739" alt="Screenshot 2020-06-05 at 08 37 50" src="https://user-images.githubusercontent.com/408568/83942255-df12ef00-a7e9-11ea-8591-53287adddca3.png">
Visualizing the election majorities.

On that note, we can close this ticket.

**Comment by Robinlovelace** [comment]
Nice!

**Comment by dcooley** [comment]
yeah good work @layik . I hope to get back to Mapdeck development in the coming weeks so I'll give you a ping to see how best to integrate this.

**Comment by layik** [comment]
all too ambitious and this package needs to walk first. Reopen if feeling good.
