### ISSUE TITLE
UI design framework

### ISSUE THREAD

**Issue by layik** [ATFutures/geoplumber#80]
Options are [quite a few](https://bestofjs.org/projects?tags=component) but the stable ones are:

- Famous [material UI](https://github.com/mui-org/material-ui)
- Uber's [baseweb](https://baseweb.design) (used in eAtlas)
- [Ant Design](https://ant.design) (by Alibaba?)

Please feel free to vote :)

**Comment by layik** [comment]
Current `bootstrap` should just disappear fully. The choice here will be making the foundation of the package and give users and future developers the right path.

**Comment by Robinlovelace** [comment]
Awesome that you're thinking about design.

**Comment by layik** [comment]
keeps getting better this
https://github.com/microsoft/fluentui

**Comment by layik** [comment]
So far github.com/uber/baseweb has not let eAtlas down and the devil we/I know.

**Comment by Robinlovelace** [comment]
Baseweb looks good to me :+1:

**Comment by layik** [comment]
The winner is Material UI due to components like: https://material-ui.com/components/data-grid/ and outclasses baseweb when it comes to sliders/etc.
